### ISSUE TITLE
I installed it, but its icon does not appear in the left column.

### ISSUE THREAD

**Issue by yiyezhangmu** [parallel-universe/gpt-copilot#1]
I installed it, but its icon does not appear in the left column.
And I restart to try ![222222222222](https://user-images.githubusercontent.com/10806567/228164974-bbd2c83a-fe34-425a-b670-386d8f0ffa17.png)times!

**Comment by parallel-universe** [comment]
The features are in the right-click context menu. Highlight text or just right click in a file to see the options.
